- frame: tool0
  pos: [0, 0, 0.05] # [m]
  angle: [0, 0, 0] # [rad]
  speed: 0.1 # [m/s]
  welding: false # [-]
- frame: tool0
  pos: [0.1, 0, 0] # [m]
  angle: [0, 0, 0] # [rad]
  speed: 0.01 # [m/s]
  welding: true # [-]
- frame: tool0
  pos: [0, 0, -0.05] # [m]
  angle: [0, 0, 0] # [rad]
  speed: 0.5 # [m/s]
  welding: false # [-]
- frame: tool0
  pos: [-0.1, 0.05, 0]
  angle: [0, 0, 0] # [rad]
  speed: 0.1 # [m/s]
  welding: false # [-]