services:
  ros:
    user: ${ROS_USER}
    env_file:
      - .env
    network_mode: host
    build:
      context: ./docker
      network: host
      dockerfile: Dockerfile
      args:
        UBUNTU_DISTRO: focal
        ROS_DISTRO: noetic
        USER: ${ROS_USER}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/home/${ROS_USER}/catkin_ws/src
      - ./scripts:/home/${ROS_USER}/scripts
    device_cgroup_rules:
      - "c 81:* rmw"
      - "c 189:* rmw"
    stdin_open: true
    tty: true
