services:
  ros:
    user: ${ROS_USER}
    env_file: .env
    network_mode: host
    build:
      context: .
      network: host
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: noetic
        USER: ${ROS_USER}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/home/${ROS_USER}/catkin_ws/src
      - ./scripts:/home/${ROS_USER}/scripts
    stdin_open: true
    tty: true
  simulation:
    user: ${SIMU_USER}
    env_file: .env
    network_mode: host
    build:
      context: .
      network: host
      dockerfile: tools/docker_ros_coppeliasim/docker/Dockerfile
      args:
        ROS_DISTRO: noetic
        USER: ${SIMU_USER}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./src:/home/${ROS_USER}/catkin_ws/src
      - ./simulation:/home/${SIMU_USER}/simulation
      - ./tools/docker_ros_coppeliasim/scripts:/home/${SIMU_USER}/scripts
    stdin_open: true
    tty: true
