services:
  ursim:
    network_mode: host
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./urcaps:/ursim/urcaps
      - ./programs:/ursim/programs
    stdin_open: true
    tty: true
