ur5_robot:
  path_urdf: "~/catkin_ws/src/controller_ur5/urdf/ur5.urdf"
  joint_names:
  - "shoulder_pan_joint"
  - "shoulder_lift_joint"
  - "elbow_joint"
  - "wrist_1_joint"
  - "wrist_2_joint"
  - "wrist_3_joint"
  original_home_joint: [0.0, -1.5708, 0.0, -1.5708, 0.0, 0.0]
  reference_frame: "base_link_inertia"
  tip_link: "tool0"

